[package]
name = "statix"
version = "0.4.1"
edition = "2018"
license = "MIT"
authors = [ "Akshay <nerdy@peppe.rs>" ]
description = "Lints and suggestions for the Nix programming language"

[lib]
name = "statix"
path = "src/lib.rs"

[[bin]]
name = "statix"
path = "src/main.rs"

[dependencies]
ariadne = "0.1.3"
rnix = "0.9.0"
clap = "3.0.0-beta.4"
ignore = "0.4.18"
thiserror = "1.0.30"
similar = "2.1.0"
vfs = { path = "../vfs" }
lib = { path = "../lib" }
toml = "0.5.8"

[dependencies.serde]
version = "1.0.68"
features = [ "derive" ]

[dependencies.serde_json]
version = "1.0.68"
optional = true

[dev-dependencies]
insta = "1.8.0"
strip-ansi-escapes = "0.1.1"

[features]
json = [ "lib/json-out", "serde_json" ]
