name: build
on:
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nix:
          - name: 2.5.1
            url: https://releases.nixos.org/nix/nix-2.5.1/install
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: cachix/install-nix-action@v15
        with:
          install_url: ${{ matrix.nix.url }}
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: enable binary cache
        uses: cachix/cachix-action@v10
        with:
          name: statix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix flake check

      - name: build statix
        run: nix build -L

      - name: build and install statix with flake-compat
        run: nix-env -if default.nix

  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nix:
          - name: 2.5.1
            url: https://releases.nixos.org/nix/nix-2.5.1/install
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.5

      - uses: cachix/install-nix-action@v15
        with:
          install_url: ${{ matrix.nix.url }}
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v10
        with:
          name: statix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: set up pinned nixpkgs
        run: echo "NIX_PATH=nixpkgs=$(nix-instantiate --eval flake-compat.nix -A defaultNix.inputs.nixpkgs.outPath | sed 's|\"||g')" >> $GITHUB_ENV

      - run: nix-shell --run "cargo test"

